### ISSUE TITLE
Codespace startup error

### ISSUE THREAD

**Issue by benwaffle** [thelukewhiting/fly-python-codespaces#1]
```
Installing the current project: fly-python-codespaces (0.1.0)
Warning: The current project could not be installed: No file/folder found for package fly-python-codespaces
If you do not want to install the current project use --no-root.
If you want to use Poetry only for dependency management but not for packaging, you can disable package mode by setting package-mode = false in your pyproject.toml file.
In a future version of Poetry this warning will become an error!
/bin/sh: 1: .: cannot open /workspaces/fly-python-codespaces/.venv/bin/activate: No such file
[9413 ms] postCreateCommand failed with exit code 2. Skipping any further user-provided commands.

Error: Command failed: /bin/sh -c poetry install && . /workspaces/fly-python-codespaces/.venv/bin/activate && fly version
    at wY (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:235:130)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async nl (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:227:4393)
    at async tl (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:227:3738)
    at async rl (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:227:2942)
    at async fs (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:227:2386)
    at async q$ (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:464:1488)
    at async iK (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:464:960)
    at async gAA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:481:3660)
    at async BC (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:481:4775)
{"outcome":"error","message":"Command failed: /bin/sh -c poetry install && . /workspaces/fly-python-codespaces/.venv/bin/activate && fly version","description":"The postCreateCommand in the devcontainer.json failed.","containerId":"d6b1961a87bf0feb0584444d2c49a8fc55148bf4a4dde68d8ff8083ecdf04d61"}
devcontainer process exited with exit code 1
Finished configuring codespace.
```

**Comment by thelukewhiting** [comment]
@benwaffle huh, I'm not able to reproduce. was it a one off or does Codespace startup fail consistently?

**Comment by benwaffle** [comment]
It happens consistently. I don't see any code that sets up a virtualenv. Have you tried creating a new codespace from main?

**Comment by thelukewhiting** [comment]
@benwaffle odd, have been creating a new codespace from main each time I test (here's [a Loom](https://www.loom.com/share/cd5aec8247284c7faa659ef7a10f4ad4?sid=b7478303-f3d9-4cf3-b6f2-84e55952a0c8))

**Comment by benwaffle** [comment]
Got it. If you click on the "Building codespace..." link while it's loading, you'll see the error. `/workspaces/fly-python-codespaces/.venv/bin/activate` doesn't exist.

**Comment by thelukewhiting** [comment]
@benwaffle ah yup, should be fixed now.
